set -g status  off
set-option -sg escape-time 10
set-window-option -g mode-keys vi
set-option -g focus-events on
set -g default-terminal "tmux-256color"
set -ga terminal-features 'xterm-256color:RGB'
# set -ga terminal-overrides ",*col*:Tc"
# set -ga terminal-features 'xterm:RGB'

